// src/data/wrapstyleImages.ts
export const WRAPSTYLE_IMAGES: string[] = [
  '/assets/lasted/car1.jpg',
  '/assets/lasted/car2.jpg',
  '/assets/lasted/car3.jpg',
  '/assets/lasted/car4.jpg',
  '/assets/lasted/car5.jpg',
  '/assets/lasted/car6.jpg',
  '/assets/lasted/car7.jpg',
  '/assets/lasted/car8.jpg',

  '/assets/lasted/car1.jpg',
  '/assets/lasted/car2.jpg',
  '/assets/lasted/car3.jpg',
  '/assets/lasted/car4.jpg',
  '/assets/lasted/car5.jpg',
  '/assets/lasted/car6.jpg',
  '/assets/lasted/car7.jpg',
  '/assets/lasted/car8.jpg',

  '/assets/lasted/car1.jpg',
  '/assets/lasted/car2.jpg',
  '/assets/lasted/car3.jpg',
  '/assets/lasted/car4.jpg',
  '/assets/lasted/car5.jpg',
  '/assets/lasted/car6.jpg',
  '/assets/lasted/car7.jpg',
  '/assets/lasted/car8.jpg',

    '/assets/lasted/car1.jpg',
  '/assets/lasted/car2.jpg',
  '/assets/lasted/car3.jpg',
  '/assets/lasted/car4.jpg',
  '/assets/lasted/car5.jpg',
  '/assets/lasted/car6.jpg',
  '/assets/lasted/car7.jpg',
  '/assets/lasted/car8.jpg',

    '/assets/lasted/car1.jpg',
  '/assets/lasted/car2.jpg',
  '/assets/lasted/car3.jpg',
  '/assets/lasted/car4.jpg',
  '/assets/lasted/car5.jpg',
  '/assets/lasted/car6.jpg',
  '/assets/lasted/car7.jpg',
  '/assets/lasted/car8.jpg',

    '/assets/lasted/car1.jpg',
  '/assets/lasted/car2.jpg',
  '/assets/lasted/car3.jpg',
  '/assets/lasted/car4.jpg',
  '/assets/lasted/car5.jpg',
  '/assets/lasted/car6.jpg',
  '/assets/lasted/car7.jpg',
  '/assets/lasted/car8.jpg',
];
